doan1/Models/Product.cs
using doan1.Data.Base;
using doan1.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace doan1.Models
{
    public class Product : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Ảnh sản phẩm")]
        [Required(ErrorMessage = "Ảnh sản phẩm không được bỏ trống")]
        public string ImageURL { get; set; }
        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "Tên sản phẩm không được bỏ trống")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Tên sản phẩm cần 3 đến 50 kí tự")]
        public string Name { get; set; }
        [Display(Name = "Giá sản phẩm")]
        [Required(ErrorMessage = "Giá sản phẩm không được bỏ trống")]
        public int Price { get; set; }
        [Display(Name = "Miêu tả sản phẩm")]
        [Required(ErrorMessage = "Miêu tả sản phẩm không được bỏ trống")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Tên sản phẩm cần 3 đến 50 kí tự")]
        public string Description { get; set; }
        [Display(Name = "Loại danh mục sản phẩm")]
        [Required(ErrorMessage = "Danh mục sản phẩm không được bỏ trống")]
        public ProductCategory ProductCategory { get; set; }

        //relationship
        //public List<Cart> Carts { get; set; }
        //public List<Order_Detail> Order_Details { get; set; }

        //Brand
        public int BrandId { get; set; }
        [ForeignKey("BrandId")]

        public Brand Brand { get; set; }
    }
}

doan1/Controllers/BrandsController.cs
using doan1.Data;
using doan1.Data.Service;
using doan1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace doan1.Controllers
{
    public class BrandsController : Controller
    {
        private readonly IBrandsService _service;
        public BrandsController(IBrandsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Get: Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Address,PhoneNumber,Email,Description")]Brand brand)
        {
            if (!ModelState.IsValid)
            {
                return View(brand);
            }
            await _service.AddAsync(brand);
            return RedirectToAction(nameof(Index));
        }

        //Get: Brands/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);

            if (brandDetails == null) return View("NotFound");
            return View(brandDetails);
        }

        //Get: Brands/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);

            if (brandDetails == null) return View("NotFound");
            return View(brandDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Address,PhoneNumber,Email,Description")]Brand brand)
        {
            if (!ModelState.IsValid)
            {
                return View(brand);
            }
            await _service.UpdateAsync(id, brand);
            return RedirectToAction(nameof(Index));
        }

        //Get: Brands/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if (brandDetails == null) return View("NotFound");
            return View(brandDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if (brandDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

doan1/Controllers/OrdersController.cs
using doan1.Data.Cart;
using doan1.Data.Service;
using doan1.Data.ViewModels;
using doan1.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;

namespace doan1.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IProductsService productsService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _productsService = productsService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            var item = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = item;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productsService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> AddToCart(int id)
        {
            var item = await _productsService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction("Details", "Products", new { id = item.Id });
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productsService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

doan1/Controllers/ProductsController.cs
using doan1.Data;
using doan1.Data.Service;
using doan1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace doan1.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductsService _service;
        public ProductsController(IProductsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var dataProducts = await _service.GetAllAsync();
            return View(dataProducts);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var dataProducts = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = dataProducts.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", dataProducts);
        }

        //Get: Products/Manage
        public async Task<IActionResult> Manage()
        {
            var dataProducts = await _service.GetAllAsync();
            return View(dataProducts);
        }

        //Get: Products/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var productDetails = await _service.GetProductByIdAsync(id);
            if (productDetails == null) return View("NotFound");
            return View(productDetails);
        }

        //Get: Products/Manage_Details/1
        public async Task<IActionResult> Manage_Details(int id)
        {
            var productDetails = await _service.GetProductByIdAsync(id);
            if (productDetails == null) return View("NotFound");

            return View(productDetails);
        }

        //Get: Products/Create
        public async Task<IActionResult> Create()
        {
            var productDropdownsData = await _service.GetNewProductDropdownsValues();

            ViewBag.Brands = new SelectList(productDropdownsData.Brands, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewProductVM product)
        {
            if (!ModelState.IsValid)
            {
                var productDropdownsData = await _service.GetNewProductDropdownsValues();

                ViewBag.Brands = new SelectList(productDropdownsData.Brands, "Id", "Name");

                return View(product);
            }

            await _service.AddNewProductAsync(product);
            return RedirectToAction(nameof(Index));
        }

        //Get: Products/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var productDetails = await _service.GetProductByIdAsync(id);
            if (productDetails == null) return View("NotFound");

            var response = new NewProductVM()
            {
                Id = productDetails.Id,
                ImageURL = productDetails.ImageURL,
                Name = productDetails.Name,
                Price = productDetails.Price,
                Description = productDetails.Description,
                ProductCategory = productDetails.ProductCategory,
                BrandId = productDetails.BrandId,
            };

            var productDropdownsData = await _service.GetNewProductDropdownsValues();
            ViewBag.Brands = new SelectList(productDropdownsData.Brands, "Id", "Name");
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewProductVM product)
        {
            if (id != product.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var productDropdownsData = await _service.GetNewProductDropdownsValues();

                ViewBag.Brands = new SelectList(productDropdownsData.Brands, "Id", "Name");

                return View(product);
            }

            await _service.UpdateProductAsync(product);
            return RedirectToAction(nameof(Index));
        }
    }
}

doan1/Views/Products/Create.cshtml
@model NewProductVM
@using doan1.Data.Enums;

@{
    ViewData["Title"] = "Thêm sản phẩm";
}

<link rel="stylesheet" href="~/css/style-create.css" />

<div class="container">
    <div class="create">
        <h2 class="title">Thêm sản phẩm</h2>
        <div class="container-create">
            <form asp-action="Create">
                <div class="bg-previewurl-square">
                    <img src="~/lib/camera-solid.svg"
                         alt=""
                         class="not-preview-square" />
                    <img class="previewurl-square" id="previewurl" />
                </div>
                <div class="form-create">
                    <label asp-for="ImageURL" class="form-label"></label>
                    <input asp-for="ImageURL" class="form-input" />
                    <span asp-validation-for="ImageURL" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-input" />
                    <span asp-validation-for="Name" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="Price" class="form-label"></label>
                    <input asp-for="Price" class="form-input" />
                    <span asp-validation-for="Price" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="Description" class="form-label"></label>
                    <input asp-for="Description" class="form-input" />
                    <span asp-validation-for="Description" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="ProductCategory" class="form-label"></label>
                    <select asp-for="ProductCategory" class="form-input" asp-items="Html.GetEnumSelectList<ProductCategory>()"></select>
                    <span asp-validation-for="ProductCategory" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="BrandId" class="form-label"></label>
                    <select asp-for="BrandId" class="form-input" asp-items="ViewBag.Brands"></select>
                    <span asp-validation-for="BrandId" class="text-error"></span>
                </div>
                <div class="act-bottom form-create">
                    <input type="submit" value="Thêm" class="act-input" />
                    <a class="btn" asp-action="Manage">Xem danh sách</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById('previewurl');
            output.src = $(this).val();
        })
    </script>
}

doan1/Views/Products/Details.cshtml
@model Product

@{
    ViewData["Title"] = "Shop me";
}

<link rel="stylesheet" href="~/css/style-product-details.css" />

<div class="container">
    <div class="product-details">
        <div class="row">
            <img src="@Model.ImageURL"
                 alt=""
                 class="img-product" />
            <div class="info-products">
                <span>Sản phẩm</span>
                <h1 class="title">@Model.Name</h1>
                <div class="catogory">
                    <img src="~/lib/tag-solid.svg"
                         alt=""
                         class="icon-catogory" />
                    <p class="desc">Loại: @Model.ProductCategory</p>
                </div>
                <p class="price-product">Giá: @Model.Price<span>đ</span></p>
                <div class="act">
                    <a class="act-buy" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id">
                        <img src="~/lib/credit-card-regular.svg"
                             alt=""
                             class="icon-atm" />
                        Mua ngay
                    </a>
                    <a asp-controller="Orders" asp-action="AddToCart" asp-route-id="@Model.Id" class="act-add-cart">
                        Thêm vào giỏ hàng
                    </a>
                </div>
            </div>
        </div>
        <div class="row-details">
            <h2 class="title-details">
                Thông tin chi tiết sản phẩm
            </h2>
            <a class="desc" asp-controller="Brands" asp-action="Details" asp-route-id="@Model.BrandId">Thương hiệu: @Model.Brand.Name</a>
            <p class="desc">Miêu tả sản phẩm: @Model.Description</p>
        </div>
    </div>
</div>

doan1/Views/Products/Edit.cshtml
@model NewProductVM
@using doan1.Data.Enums;

@{
    ViewData["Title"] = "Thêm sản phẩm";
}

<link rel="stylesheet" href="~/css/style-create.css" />

<div class="container">
    <div class="create">
        <h2 class="title">Sửa sản phẩm</h2>
        <div class="container-create">
            <form asp-action="Edit">
                <div class="bg-previewurl-square">
                    <img src="~/lib/camera-solid.svg"
                         alt=""
                         class="not-preview-square" />
                    <img class="previewurl-square" id="previewurl" />
                </div>
                <div class="form-create">
                    <label asp-for="ImageURL" class="form-label"></label>
                    <input asp-for="ImageURL" class="form-input" />
                    <span asp-validation-for="ImageURL" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-input" />
                    <span asp-validation-for="Name" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="Price" class="form-label"></label>
                    <input asp-for="Price" class="form-input" />
                    <span asp-validation-for="Price" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="Description" class="form-label"></label>
                    <input asp-for="Description" class="form-input" />
                    <span asp-validation-for="Description" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="ProductCategory" class="form-label"></label>
                    <select asp-for="ProductCategory" class="form-input" asp-items="Html.GetEnumSelectList<ProductCategory>()"></select>
                    <span asp-validation-for="ProductCategory" class="text-error"></span>
                </div>
                <div class="form-create">
                    <label asp-for="BrandId" class="form-label"></label>
                    <select asp-for="BrandId" class="form-input" asp-items="ViewBag.Brands"></select>
                    <span asp-validation-for="BrandId" class="text-error"></span>
                </div>
                <div class="act-bottom form-create">
                    <input type="submit" value="Chỉnh sửa" class="act-input" />
                    <a class="btn" asp-action="Manage">Xem danh sách</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById('previewurl');
            output.src = $(this).val();
        })

        $(document).ready(function () {
            var output = document.getElementById('previewurl');
            output.src = $("#ImageURL").val();
        })
    </script>
}

doan1/Views/Products/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "San pham";
}


<!-- ***** Header Area End ***** -->
<!-- container -->
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-content">
                <!-- ***** Banner Start ***** -->
                <div class="main-banner">
                    <div class="row">
                        <div class="col-lg-7">
                            <div class="header-text">
                                <h6>Welcome</h6>
                                <h4><em>LUXURY</em></h4>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ***** Banner End ***** -->
            <!-- ***** Most Popular Start ***** -->
            <div class="most-popular">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="heading-section ">
                            <h4><em>Danh Mục</em> <span class="subtext">Sản Phẩm</span></h4>
                            <div class="row ">

                                <div class="col-lg-12">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ***** Most Popular End ***** -->
                <!-- ***** Gaming Library Start ***** -->
                <div id="SanPham" class="gaming-library">
                    <div class="col-lg-12">
                        <div class="heading-section">
                            <h4><em>Sản Phẩm</em> <span class="subtext">Ưa Chuộng</span></h4>
                        </div>
                        @foreach (var item in Model)
                        {
                            <div class="item-library">
                                <ul>
                                    <li><img src="~/images/1.jpg" alt="" class="templatemo-item"></li>
                                    <li><h4>Nhẫn Bạc EMERAALD</h4><span>48K Lượt Mua</span></li>
                                    <li><h4>Xuất Xứ:</h4><span>China</span></li>
                                    <li><h4>Giá Bán</h4><span>780.000đ</span></li>

                                    <li><div class="main-border-button border-no-active"><a href="#">Thêm Giỏ Hàng</a></div></li>
                                </ul>
                            </div>
                        }
                    </div>
                </div>
                <!-- ***** Gaming Library End ***** -->
            </div>
        </div>
    </div>
</div>

doan1/Views/Products/Manage.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "Quản lý sản phẩm";
}

<link rel="stylesheet" href="~/css/style-brand.css" />

<div class="Brand">
    <div class="container">
        <h2 class="title">Danh sách sản phẩm</h2>
        <div class="list-brand">
            @foreach (var item in Model)
            {
                <div class="item-brand">
                    <div class="bg-logo">
                        <img src="@item.ImageURL"
                             alt=""
                             class="logo-product" />
                    </div>
                    <h3 class="name">@item.Name</h3>
                    <div class="action">
                        <a class="act act-edit" asp-action="Edit" asp-route-id="@item.Id" >Edit</a>
                        <a class="act act-details" asp-action="Manage_Details" asp-route-id="@item.Id">Details</a>
                        <a href="" class="act act-delete">Delete</a>
                    </div>
                </div>
            }
        </div>
    </div>
    @await Html.PartialAsync("_CreateItem", "Products")
</div>

doan1/Views/Products/Manage_Details.cshtml
@model Product

@{
    ViewData["Title"] = "Chi tiết sản phẩm";
}

<link rel="stylesheet" href="~/css/style-create.css" />

<div class="container">
    <div class="create">
        <h2 class="title">Thông tin chi tiết @Model.Name</h2>
        <div class="container-create">
            <div class="bg-previewurl-square">
                <img src="~/lib/camera-solid.svg"
                     alt=""
                     class="not-preview-square" />
                <img class="previewurl-square" id="previewurl" />
            </div>
            <div class="form-create">
                <label asp-for="ImageURL" class="form-label"></label>
                <input asp-for="ImageURL" class="form-input" readonly/>
                <span asp-validation-for="ImageURL" class="text-error"></span>
            </div>
            <div class="form-create">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-input" readonly />
                <span asp-validation-for="Name" class="text-error"></span>
            </div>
            <div class="form-create">
                <label asp-for="Price" class="form-label"></label>
                <input asp-for="Price" class="form-input" readonly />
                <span asp-validation-for="Price" class="text-error"></span>
            </div>
            <div class="form-create">
                <label asp-for="Description" class="form-label"></label>
                <input asp-for="Description" class="form-input" readonly />
                <span asp-validation-for="Description" class="text-error"></span>
            </div>
            <div class="form-create">
                <label asp-for="ProductCategory" class="form-label"></label>
                <input asp-for="ProductCategory" class="form-input" readonly />
                <span asp-validation-for="ProductCategory" class="text-error"></span>
            </div>
            <div class="form-create">
                <label asp-for="Brand.Name" class="form-label"></label>
                <input asp-for="Brand.Name" class="form-input" readonly />
                <span asp-validation-for="Brand.Name" class="text-error"></span>
            </div>
            <div class="act-bottom form-create">
                <a class="btn" asp-action="Edit" asp-route-id="@Model.Id">Chỉnh sửa</a>
                <a class="btn" asp-action="Manage">Xem danh sách</a>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('previewurl');
            output.src = $("#ImageURL").val();
        })
    </script>
}